name: kudosapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # core
  provider: ^4.0.5+1

  get_it: ^4.0.2

  easy_localization: ^2.3.2

  cloud_firestore: ^0.13.5

  firebase_storage: ^3.1.5

  flutter_svg: ^0.17.4

  flutter_cache_manager: ^1.2.2

  file_picker: ^1.7.1

  uuid: ^2.0.4

  path: ^1.6.4

  cached_network_image: ^2.2.0+1

  semaphore: ^0.1.4

  rxdart: ^0.24.0

  event_bus: ^1.1.1

  # auth
  google_sign_in: ^4.4.4

  firebase_auth: ^0.16.0

  equatable: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/translations/
