name: kudosapp
description: A new Flutter application.

version: 0.0.2+10

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # localization

  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0

  # system

  uuid: ^3.0.2

  path: ^1.8.0

  semaphore: ^0.1.4

  rxdart: ^0.26.0

  event_bus: ^2.0.0

  sprintf: ^6.0.0

  sortedmap: ^0.5.0

  sorted_list: ^0.1.0

  mutex: ^3.0.0

  equatable: ^2.0.0

  url_launcher: ^6.0.2

  # core

  provider: ^5.0.0

  get: ^3.26.0

  get_it: ^6.0.0

  # firebase

  firebase_core: ^1.0.2

  cloud_firestore: ^1.0.2

  firebase_storage: ^8.0.0

  firebase_messaging: ^9.0.1

  firebase_crashlytics: ^1.0.0

  firebase_analytics: ^7.1.1

  # auth

  firebase_auth: ^1.0.1

  google_sign_in: ^5.0.1

  # images

  cached_network_image: ^3.0.0-nullsafety

  image_picker: ^0.7.3

  flutter_svg: ^0.21.0-nullsafety.0

  flutter_cache_manager: ^3.0.0-nullsafety.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/

# https://marketplace.visualstudio.com/items?itemName=localizely.flutter-intl
flutter_intl:
  enabled: true

flutter_icons:
  image_path_ios: "assets/icons/app_icon.png"
  image_path_android: "assets/icons/app_icon.png"
  adaptive_icon_foreground: "assets/icons/app_icon_transparent.png"
  adaptive_icon_background: "assets/icons/app_icon_gradient.png"
  android: true
  ios: true
