name: kudosapp
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # core
  provider: ^4.0.5+1

  get_it: ^4.0.2

  cloud_firestore: ^0.13.5

  flutter_svg: ^0.17.4

  flutter_cache_manager: ^1.2.2

  # auth
  google_sign_in: ^4.4.4

  firebase_auth: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
