name: Build and deploy

on:
  pull_request:
    branches:
      - master

env:
  flutter_version: "1.17.5"

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Cache Flutter dependencies
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.os }}-flutter-${{ env.flutter_version }}
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.flutter_version }}
    - name: Install dependencies
      run: flutter pub get
      working-directory: src
    - name: Add google-services.json
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: src/android/app/google-services.json
        contents: ${{secrets.android_google_services}}
        write-mode: overwrite
    - name: Add key.properties
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: src/android/key.properties
        contents: ${{secrets.android_key_properties}}
        write-mode: overwrite
    - name: Add key.jks
      uses: DamianReeves/write-file-action@v1.0
      with:
        path: src/android/key.jks
        contents: |
          echo ${{secrets.android_key}} | base64 --decode
        write-mode: overwrite
    - name: Display list
      run: |
        pwd
        cd src/android && ls -al
        shasum key.jks
      shell: bash
    - name: Build Android app
      run: flutter build apk
      working-directory: src

