name: Build and deploy

on:
  pull_request:
    branches:
      - master

env:
  flutter_version: "1.17.5"

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - name: Cache Flutter dependencies
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.os }}-flutter-${{ env.flutter_version }}
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.flutter_version }}
    - name: Install dependencies
      run: flutter pub get
      working-directory: src
    - name: Build Android app
      run: flutter build apk
      working-directory: src

