name: Build and deploy

on:
  pull_request:
    branches:
      - master

env:
  flutter_version: "1.17.5"
  java_version: "12.x"

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}
    - name: Cache flutter dependencies
      uses: actions/cache@v1
      with:
        path: /opt/hostedtoolcache/flutter
        key: ${{ runner.os }}-flutter-${{ env.flutter_version }}
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.flutter_version }}
    - name: Install app dependencies
      run: flutter pub get
      working-directory: src
    - name: Add google-services.json
      run: |
        echo "$FIREBASE_CONFIG" > src/android/app/google-services.json
      env:
        FIREBASE_CONFIG: ${{secrets.android_google_services}}
      shell: bash
    - name: Add key.properties
      run: |
        echo "$KEY_PROPS" > src/android/key.properties
      env:
        KEY_PROPS: ${{secrets.android_key_properties}}
      shell: bash
    - name: Add key
      run: |
        echo "$KEYSTORE" | base64 --decode > src/android/key.jks
      env:
        KEYSTORE: ${{secrets.android_key}}
      shell: bash
    - name: Build Android app
      run: flutter build apk
      working-directory: src
    - name: Upload apk to App Center
      uses: wzieba/AppCenter-Github-Action@v1.1.1
      with:
        appName: softeqdevelopment/Kudos.Android
        token: ${{secrets.app_center_android}}
        group: Dev Team
        file: src/build/app/outputs/apk/release/app-release.apk
