name: Release iOS

on:
  push:
    branches:
      # - 'releases/**'
      - 'feature/ios-release'
  #   tags:
  #     - release_**

env:
  flutter_version: "1.17.5"
  java_version: "12.x"
  appcenter_cli_version: "2.6.3"

jobs:
  build:
    defaults:
      run:
        working-directory: src
    runs-on: macos-latest
    env:
      XC_ARCHIVE_PATH: build/ios/ci/Runner.xcarchive
      XC_EXPORT_PATH: build/ios/ci/RunnerExport
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}

    - name: Cache flutter
      uses: actions/cache@v1
      with:
        path: /Users/runner/hostedtoolcache/flutter
        key: ${{ runner.os }}-flutter-${{ env.flutter_version }}

    - name: Use flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.flutter_version }}

    - name: Cache Pods dependencies
      uses: actions/cache@v1
      with:
        path: ios/Pods
        key: ${{ runner.OS }}-pods-${{ hashFiles('**/ios/Podfile.lock') }}
        restore-keys: |
          ${{ runner.OS }}-pods-

    - name: Install app dependencies
      run: flutter pub get

    - name: Add GoogleService-Info.plist
      run: |
        echo "$FIREBASE_CONFIG" > ios/Runner/GoogleService-Info.plist
      env:
        FIREBASE_CONFIG: ${{ secrets.ios_google_services }}

    - name: Build app
      run: flutter build ios --release --no-codesign

    - name: Decrypt
      run: |
        cd ../certificates/ios/
        zsh decrypt.sh
      env:
        IOS_PASSPHRASE: ${{ secrets.ios_passphrase }}

    - name: Configure Keychain & Code Signing
      run: |
        cd ../certificates/ios/
        echo "Install profiles..."
        mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
        UUID=`/usr/libexec/PlistBuddy -c 'Print :UUID' /dev/stdin <<< $(security cms -D -i ./dev.mobileprovision)`
        cp dev.mobileprovision ~/Library/MobileDevice/Provisioning\ Profiles/$UUID.mobileprovision
        ls ~/Library/MobileDevice/Provisioning\ Profiles
        echo "Done."
        echo "Install dev certificate..."
        echo "Configure keychain"
        security create-keychain -p "" "$KEYCHAIN"
        security list-keychains -d user -s "$KEYCHAIN" $(security list-keychains -d user | sed s/\"//g)
        security list-keychains
        security default-keychain -s "$KEYCHAIN"
        security set-keychain-settings "$KEYCHAIN"
        security unlock-keychain -p "" "$KEYCHAIN"
        echo "Import..."
        security import dev.p12 -k "$KEYCHAIN" -P "$IOS_PASSPHRASE" -T "/usr/bin/codesign"
        security set-key-partition-list -S apple-tool:,apple: -s -k "" $KEYCHAIN
        echo "Done."
      env:
        IOS_PASSPHRASE: ${{ secrets.ios_passphrase }}
        KEYCHAIN: build.keychain

    - name: Archive
      run: |
        cd ios
        xcodebuild \
          -workspace Runner.xcworkspace \
          -scheme Runner \
          -sdk iphoneos \
          -configuration Release \
          archive \
          -archivePath "$XC_ARCHIVE_PATH"

    - name: Export for distribution
      run: |
        xcodebuild \
          -exportArchive \
          -archivePath "$XC_ARCHIVE_PATH" \
          -exportOptionsPlist exportOptions.plist \
          -exportPath "$XC_EXPORT_PATH"

    - name: Cache NPM dependencies (App Center)
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-

    - name: Deploy to App Center
      run: |
        npm install appcenter-cli@${{ env.appcenter_cli_version}}
        npx appcenter distribute release \
          --token "${{ secrets.app_center }}" \
          --app "softeqdevelopment/Kudos.iOS" \
          --group "Dev Team" \
          --file "$XC_EXPORT_PATH/Runner.ipa" \
          --release-notes "New release" \
          --debug
