name: Release Android

on:
  push:
    branches:
      - 'releases/**'
    tags:
      - release_**

env:
  flutter_version: "1.22.1"
  java_version: "12.x"
  appcenter_cli_version: "2.6.3"

jobs:
  build:
    defaults:
      run:
        working-directory: src
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-java@v1
      with:
        java-version: ${{ env.java_version }}

    - name: Cache flutter
      uses: actions/cache@v1
      with:
        path: /Users/runner/hostedtoolcache/flutter
        key: ${{ runner.os }}-flutter-${{ env.flutter_version }}

    - name: Use flutter
      uses: subosito/flutter-action@v1
      with:
        flutter-version: ${{ env.flutter_version }}

    - name: Add local.properties
      run: echo "ndk.dir=${ANDROID_HOME}/ndk-bundle" > android/local.properties

    - name: Install app dependencies
      run: flutter pub get

    - name: Add google-services.json
      run: |
        echo "$FIREBASE_CONFIG" > android/app/google-services.json
      env:
        FIREBASE_CONFIG: ${{ secrets.android_google_services }}

    - name: Add key.properties
      run: |
        echo "$KEY_PROPS" > android/key.properties
      env:
        KEY_PROPS: ${{ secrets.android_key_properties }}

    - name: Add key
      run: |
        echo "$KEYSTORE" | base64 --decode > android/key.jks
      env:
        KEYSTORE: ${{ secrets.android_key }}

    - name: Build app
      run: flutter build apk

    - name: Cache NPM dependencies (App Center)
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.OS }}-npm-

    - name: Deploy to App Center
      run: |
        npm install appcenter-cli@${{ env.appcenter_cli_version}}
        npx appcenter distribute release \
          --token "${{ secrets.app_center }}" \
          --app "softeqdevelopment/Kudos.Android" \
          --group "Dev Team" \
          --file "build/app/outputs/apk/release/app-release.apk" \
          --release-notes "New release" \
          --debug
